# Generated by Django 2.2.12 on 2020-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('subjects', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=150)),
                ('emailAdress', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Contact_info',
                'verbose_name_plural': 'Contact_infos',
            },
        ),
        migrations.CreateModel(
            name='Newletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Newletter',
                'verbose_name_plural': 'Newletters',
            },
        ),
        migrations.CreateModel(
            name='ReseauxSociau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('icon-facebook', 'facebook'), ('icon-twitter', 'twitter'), ('icon-instagram', 'instagram'), ('icon-linkedin', 'linkedin')], max_length=50)),
                ('lien', models.URLField()),
            ],
            options={
                'verbose_name': 'ReseauxSociau',
                'verbose_name_plural': 'ReseauxSociaux',
            },
        ),
        migrations.CreateModel(
            name='Siteinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_index', models.CharField(max_length=250)),
                ('description_index', models.TextField()),
                ('titre_dj', models.CharField(max_length=150)),
                ('description_dj', models.TextField()),
                ('titre_event', models.CharField(max_length=150)),
                ('description_event', models.TextField()),
                ('titre_about', models.CharField(max_length=150)),
                ('description_about', models.TextField()),
                ('titre_contact', models.CharField(max_length=150)),
                ('description_contact', models.TextField()),
                ('copyrights', models.CharField(max_length=150)),
                ('background_index', models.ImageField(upload_to='logo/background_index')),
                ('about_footer_description', models.CharField(max_length=150)),
                ('image_video_footer', models.ImageField(upload_to='image/footer')),
                ('lien_video_footer', models.URLField()),
            ],
            options={
                'verbose_name': 'Siteinfo',
                'verbose_name_plural': 'Siteinfos',
            },
        ),
    ]
