# Generated by Django 2.2.12 on 2020-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_about_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='fonction',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
