# Generated by Django 2.2.12 on 2020-09-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_our_team_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='background_index',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='background_dj',
            field=models.ImageField(null=True, upload_to='logo/background_dj'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='description_single',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='titre_single',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='description_dj',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='titre_dj',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
