# Generated by Django 2.2.12 on 2020-09-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200907_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='background_dj',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='background_index',
            field=models.ImageField(null=True, upload_to='logo/background_index'),
        ),
    ]
