# Generated by Django 2.2.12 on 2020-09-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200907_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='background_index',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='image_index',
            field=models.ImageField(null=True, upload_to='logo/image_index'),
        ),
    ]
