# Generated by Django 2.2.12 on 2020-09-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200907_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='image_index',
        ),
    ]
