# Generated by Django 2.2.12 on 2020-09-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_siteinfo_image_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='description_single',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='bg_index',
            field=models.ImageField(null=True, upload_to='background_index'),
        ),
    ]
