# Generated by Django 2.2.12 on 2020-09-10 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200909_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newletter',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newletter',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newletter',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='fonction',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='our_team',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reseauxsociau',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reseauxsociau',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reseauxsociau',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reseauxsociau',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='bg_index',
            field=models.ImageField(upload_to='background_index'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='titre_dj',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='titre_single',
            field=models.CharField(max_length=150),
        ),
    ]
