# Generated by Django 2.2.12 on 2020-09-07 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showdj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Created_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=150)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'Created_by',
                'verbose_name_plural': 'Created_by',
            },
        ),
        migrations.AlterField(
            model_name='show',
            name='musique',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='show',
            name='created_by',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='show_created', to='showdj.Created_by'),
            preserve_default='true',
        ),
    ]
