# Generated by Django 2.2.12 on 2020-09-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showdj', '0002_auto_20200907_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='created_by',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='show_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Created_by',
        ),
    ]
